#!/sbin/busybox sh

# $1 - "cpus_boosted"
# $2 - value=

if [ "a$2" != "a" ]; then
	cpus_boosted=$2;

	echo ${cpus_boosted} > /sys/module/msm_hotplug/cpus_boosted;
	echo ${cpus_boosted} > /sys/kernel/intelli_plug/cpus_boosted;
fi;

echo ${cpus_boosted};
