#!/sbin/busybox sh

# $1 - "fast_charge"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$fast_charge";
else
	fast_charge=$2;
	echo "$fast_charge";
fi;

case "${fast_charge}" in
	0)
		echo "0" > /sys/kernel/fast_charge/force_fast_charge
	;;
	1)
		echo "1" > /sys/kernel/fast_charge/force_fast_charge
		echo "1200" > /sys/kernel/fast_charge/fast_charge_level
	;;
	2)
		echo "2" > /sys/kernel/fast_charge/force_fast_charge
		echo "500" > /sys/kernel/fast_charge/fast_charge_level
	;;
	3)
		echo "2" > /sys/kernel/fast_charge/force_fast_charge
		echo "900" > /sys/kernel/fast_charge/fast_charge_level
	;;
	4)
		echo "2" > /sys/kernel/fast_charge/force_fast_charge
		echo "1200" > /sys/kernel/fast_charge/fast_charge_level
	;;
	5)
		echo "2" > /sys/kernel/fast_charge/force_fast_charge
		echo "1500" > /sys/kernel/fast_charge/fast_charge_level
	;;
	6)
		echo "2" > /sys/kernel/fast_charge/force_fast_charge
		echo "2000" > /sys/kernel/fast_charge/fast_charge_level
	;;
	*)
		fast_charge=0;
	;;
esac;
