#!/sbin/busybox sh

# use this script only if you are tuning existing file!
# script check if $2 really exist.

if [ "a$2" != "a" ]; then

	filename=$(basename "$2");

	if [ "a$3" == "a" ]; then
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
	else
		evalcmd='eval "$filename=$3"';
		eval $evalcmd;
		evalcmd='eval "echo \$$filename"';
		eval $evalcmd;
		if [ -f $2 ]; then
			stop mpdecision;
			echo "$3" > $2;
			if [ "$intelli_plug_active" == "1" ]; then
				[ -f /system/lib/hw/power.msm8974.so.bak ] || mv /system/lib/hw/power.msm8974.so /system/lib/hw/power.msm8974.so.bak;
				stop mpdecision;
			else
				[ -f /system/lib/hw/power.msm8974.so ] || mv /system/lib/hw/power.msm8974.so.bak /system/lib/hw/power.msm8974.so;
				stop mpdecision;
				start mpdecision;
			fi;
			if [ "$enabled" == "Y" ]; then
				stop thermal-engine;
			else
				stop thermal-engine;
				start thermal-engine;
			fi;
		fi;
	fi;
fi;

