#!/sbin/busybox sh

# $1 - "hotplug"
# $2 - value=

BB=/sbin/busybox

if [ "a$2" != "a" ]; then
	hotplug=$2;

	case "${hotplug}" in
		intelli)
			/system/bin/stop mpdecision
			echo "1" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_disable;
#			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "$eco_mode_active" > /sys/kernel/intelli_plug/eco_mode_active;
			echo "$strict_mode_active" > /sys/kernel/intelli_plug/strict_mode_active;
			echo "$wake_boost_active" > /sys/kernel/intelli_plug/wake_boost_active;
			echo "$touch_boosted_cpus" > /sys/kernel/intelli_plug/touch_boosted_cpus;
			echo "1" > /sys/kernel/intelli_plug/intelli_plug_active;
		;;
		mpdecision)
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
#			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			if [ "$(ps | grep "mpdecision" | wc -l)" -le "1" ]; then
				/system/bin/start mpdecision
				$BB renice -n -20 -p $(pgrep -f "/system/bin/mpdecision");
			fi;
			echo "0" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_disable;
		;;
		msm_hotplug)
			/system/bin/stop mpdecision
			echo "1" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_disable;
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
#			echo "0" > /sys/kernel/alucard_hotplug/hotplug_enable;
			echo "$cpus_boosted" > /sys/module/msm_hotplug/cpus_boosted;
			echo "$max_cpus_online" > /sys/module/msm_hotplug/max_cpus_online;
			echo "1" > /sys/module/msm_hotplug/msm_enabled;
		;;
		alucard)
			/system/bin/stop mpdecision
			echo "1" > /sys/devices/system/cpu/cpu0/rq-stats/hotplug_disable;
			echo "0" > /sys/kernel/intelli_plug/intelli_plug_active;
			echo "0" > /sys/module/msm_hotplug/msm_enabled;
			echo "$maxcoreslimit" > /sys/kernel/alucard_hotplug/maxcoreslimit;
			echo "$maxcoreslimit_sleep" > /sys/kernel/alucard_hotplug/maxcoreslimit_sleep;
			echo "1" > /sys/kernel/alucard_hotplug/hotplug_enable;
		;;
		*)
			hotplug=msm_hotplug;
		;;
	esac;
fi;

echo ${hotplug};

