#!/sbin/busybox sh

# $1 - "ksm_control"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$ksm_control";
else
	ksm_control=$2;
	echo "$ksm_control";
fi;

case "${ksm_control}" in
	off)
		echo "0" > sys/kernel/mm/ksm/run
	;;
	on)
		echo "1" > sys/kernel/mm/ksm/run
		echo "1500" > /sys/kernel/mm/ksm/sleep_millisecs;
		echo "256" > /sys/kernel/mm/ksm/pages_to_scan;
	;;
	*)
		ksm_control=off;
	;;
esac;
