#!/sbin/busybox sh

# $1 - "max_cpus_online"
# $2 - value=

if [ "a$2" != "a" ]; then
	max_cpus_online=$2;

	case "${max_cpus_online}" in
		1)
#			echo "1" > /sys/kernel/alucard_hotplug/max_cpus_online;
			echo "1" > /sys/module/msm_hotplug/max_cpus_online;
			echo "1" > /sys/kernel/intelli_plug/max_cpus_online;
		;;
		2)
#			echo "2" > /sys/kernel/alucard_hotplug/max_cpus_online;
			echo "2" > /sys/module/msm_hotplug/max_cpus_online;
			echo "2" > /sys/kernel/intelli_plug/max_cpus_online;
		;;
		3)
#			echo "3" > /sys/kernel/alucard_hotplug/max_cpus_online;
			echo "3" > /sys/module/msm_hotplug/max_cpus_online;
			echo "3" > /sys/kernel/intelli_plug/max_cpus_online;
		;;
		4)
#			echo "4" > /sys/kernel/alucard_hotplug/max_cpus_online;
			echo "4" > /sys/module/msm_hotplug/max_cpus_online;
			echo "4" > /sys/kernel/intelli_plug/max_cpus_online;
		;;
		*)
			max_cpus_online=4;
		;;
	esac;
fi;

echo ${max_cpus_online};
