#!/system/xbin/bash

# $1 - "min_cpus_online"
# $2 - value=

if [ "a$2" != "a" ]; then
	min_cpus_online=$2;

	case "${min_cpus_online}" in
		1)
#			echo "1" > /sys/kernel/alucard_hotplug/min_cpus_online;
			echo "1" > /sys/module/msm_hotplug/min_cpus_online;
			echo "1" > /sys/kernel/intelli_plug/min_cpus_online;
		;;
		2)
#			echo "2" > /sys/kernel/alucard_hotplug/min_cpus_online;
			echo "2" > /sys/module/msm_hotplug/min_cpus_online;
			echo "2" > /sys/kernel/intelli_plug/min_cpus_online;
		;;
		3)
#			echo "3" > /sys/kernel/alucard_hotplug/min_cpus_online;
			echo "3" > /sys/module/msm_hotplug/min_cpus_online;
			echo "3" > /sys/kernel/intelli_plug/min_cpus_online;
		;;
		4)
#			echo "4" > /sys/kernel/alucard_hotplug/min_cpus_online;
			echo "4" > /sys/module/msm_hotplug/min_cpus_online;
			echo "4" > /sys/kernel/intelli_plug/min_cpus_online;
		;;
		*)
			min_cpus_online=1;
		;;
	esac;
fi;

echo ${min_cpus_online};
