#!/sbin/busybox sh

# $1 - "morpheus_background_process"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$morpheus_background_process";
else
	morpheus_background_process=$2;
	echo "$morpheus_background_process";
fi;

case "${morpheus_background_process}" in
	0)
		pkill -f "/sbin/ext/morpheus.sh";
		sed -i "s/morpheus_background_process=[0-1]*/morpheus_background_process=0/g" /sbin/ext/morpheus.sh;
	;;
	1)
		sed -i "s/morpheus_background_process=[0-1]*/morpheus_background_process=1/g" /sbin/ext/morpheus.sh;
		if [ $(pgrep -f "morpheus.sh" | wc -l) -eq "0" ]; then
			nohup /sbin/ext/morpheus.sh > /dev/null 2>&1;
		fi;
		CORTEX=$(pgrep -f "/sbin/ext/morpheus.sh");
		echo "-900" > /proc/"$CORTEX"/oom_score_adj;
	;;
	*)
		morpheus_background_process=1;
	;;
esac;
