#!/sbin/busybox sh

# $1 - "suspend_defer_time"
# $2 - value=

if [ "a$2" != "a" ]; then
	suspend_defer_time=$2;

#	echo "$suspend_defer_time" > /sys/kernel/alucard_hotplug/suspend_defer_time;
	echo "$suspend_defer_time" > /sys/module/msm_hotplug/suspend_defer_time;
	echo "$suspend_defer_time" > /sys/kernel/intelli_plug/suspend_defer_time;
fi;

echo ${suspend_defer_time};
