#!/sbin/busybox sh

# $1 - "zramtweaks"
# $2 - value=

if [ "a$2" == "a" ]; then
	echo "$zramtweaks";
else
	zramtweaks=$2;
	echo "$zramtweaks";
fi;

case "${zramtweaks}" in
	1)
		if [ `cat /proc/swaps | grep 50000 |  wc -l` != "1" ]; then
			if [ -e /dev/block/zram0 ]; then
				# for on the fly changes we need to shutdown ZRAM first
				swapoff /dev/block/zram0 >/dev/null 2>&1;
				echo "1" > /sys/block/zram0/reset;
				# setting size of each ZRAM swap drives
				echo "52428800" > /sys/block/zram0/disksize;
				# creating SWAPS from ZRAM drives
				mkswap /dev/block/zram0 >/dev/null;
				echo 1 > /sys/block/zram0/initstate;
				# activating ZRAM swaps with the same priority to load balance ram swapping
				chmod 755 /system/xbin/swapon;
				swapon /dev/block/zram0 -p 20 >/dev/null 2>&1;
			fi;
		fi;
	;;
	2)
		if [ `cat /proc/swaps | grep 100000 |  wc -l` != "1" ]; then
			if [ -e /dev/block/zram0 ]; then
				# for on the fly changes we need to shutdown ZRAM first
				swapoff /dev/block/zram0 >/dev/null 2>&1;
				echo "1" > /sys/block/zram0/reset;
				# setting size of each ZRAM swap drives
				echo "104857600" > /sys/block/zram0/disksize;
				# creating SWAPS from ZRAM drives
				mkswap /dev/block/zram0 >/dev/null;
				chmod 755 /system/xbin/swapon;
				echo 1 > /sys/block/zram0/initstate;
				# activating ZRAM swaps with the same priority to load balance ram swapping
				swapon /dev/block/zram0 -p 20 >/dev/null 2>&1;
			fi;
		fi;
	;;
	3)
		if [ `cat /proc/swaps | grep 200000 |  wc -l` != "1" ]; then
			if [ -e /dev/block/zram0 ]; then
				# for on the fly changes we need to shutdown ZRAM first
				swapoff /dev/block/zram0 >/dev/null 2>&1;
				echo "1" > /sys/block/zram0/reset;
				# setting size of each ZRAM swap drives
				echo "209715200" > /sys/block/zram0/disksize;
				# creating SWAPS from ZRAM drives
				mkswap /dev/block/zram0 >/dev/null;
				chmod 755 /system/xbin/swapon;
				echo 1 > /sys/block/zram0/initstate;
				# activating ZRAM swaps with the same priority to load balance ram swapping
				swapon /dev/block/zram0 -p 20 >/dev/null 2>&1;
			fi;
		fi;
	;;
	4)
		if [ -e /dev/block/zram0 ]; then
			swapoff /dev/block/zram0 >/dev/null 2>&1;
			echo "1" > /sys/block/zram0/reset;
		fi;
	;;
	*)
		zramtweaks=4;
	;;
esac;
