#!/sbin/busybox sh

if [ `pgrep -f push-actions/clean_ram_cache |  wc -l` \< 3 ]; then
	mount -o remount,rw /;
	mount -o remount,rw /system;
	MEM_FREE=`free | grep Mem | awk '{ print $4 }'`;
	CALC_MEM=`echo $(($MEM_FREE/1024))M`;
	echo "FREE BEFORE $CALC_MEM" > /tmp/ram_clean;
	chmod 777 /tmp/ram_clean;
	sync;
	sysctl -w vm.drop_caches=3 > /dev/null 2>&1;
	sysctl -w vm.drop_caches=1 > /dev/null 2>&1;
	MEM_FREE_AFTER=`free | grep Mem | awk '{ print $4 }'`;
	CALC_MEM_AFTER=`echo $(($MEM_FREE_AFTER/1024))M`;
	echo "FREE AFTER $CALC_MEM_AFTER" >> /tmp/ram_clean;
	RAM_LOG=`cat /tmp/ram_clean`;
	echo "$RAM_LOG";
	rm -f $RAM_LOG;
else
	# Anti smart user protection!
	echo "Please wait!";
fi;
