#!/system/xbin/bash
export PATH="/res/customconfig/actions/push-actions:${PATH}";

BB=/sbin/busybox

if [ "a$2" == "a" ]; then
	echo "$config_backup_restore";
else
	config_backup_restore=$2;
	echo "$config_backup_restore";
fi;

if [ "$(pgrep -f "/res/customconfig/actions/push-actions/config_backup_restore" | wc -l)" -le "4" ]; then

	$BB mount -o remount,rw /;
	LOCK_FILE="/data/.chaos/restore_running";
	PROFILE=`cat /data/.chaos/.active.profile`;

	case "${config_backup_restore}" in
		1)
			echo "Backing up your $PROFILE config file.";
			cp /data/.chaos/${PROFILE}.profile /data/.chaos/${PROFILE}.profile_backup;
			cp /data/.chaos/${PROFILE}.profile /sdcard/${PROFILE}.profile_backup;
			echo "Backup Done!";
		;;
		2)
			file1="/data/.chaos/${PROFILE}.profile";
			file2="/data/.chaos/${PROFILE}.profile_backup";
			# if someone full wipe the system, then use the profile_backup from sd-card
			if [ ! -f $file2 ]; then
				file2="/sdcard/${PROFILE}.profile_backup";
			fi;

			if [ ! -f $file1 ] || [ ! -f $file2 ]; then
				echo "File not found!";
				exit;
			fi;

			(
				# read in file1->line1
				while read line1; do
					# split the config into variables where we find "="
					line1_1=$(echo $line1 | cut -f 1 -d '=');
					line1_2=$(echo $line1 | cut -f 2 -d '=');

					# grep the content from backup-file ...
					line2=$(grep "^${line1_1}\=" $file2)
					# ... and also split into variables
					line2_1=$(echo $line2 | cut -f 1 -d '=');
					line2_2=$(echo $line2 | cut -f 2 -d '=');

					# compare config- and backup-file
					if [ "a${line1_1}" != "a${line2_1}" ]; then
						# nothing to do -> continue the loop
						continue;
					else
						# if backup-file has different values, then restore it
						if [ "a${line1_2}" != "a${line2_2}" ]; then
							if [ "${line2_2}" != "" ]; then
								/sbin/busybox sed -i "s/${line1_1}=${line1_2}/${line2_1}=${line2_2}/" $file1;
								echo "edit: ${line1_1}=${line1_2} -> ${line2_1}=${line2_2}";
							fi;
						else
							# nothing to do -> continue the loop
							# echo "not_edit: ${line1_1}=${line1_2} -> ${line2_1}=${line2_2}";
							continue;
						fi;
					fi;
				done<$file1
				$BB sh /res/user_uci_test_run.sh > /dev/null;
			)&
		;;
		3)
			(
				rm -f /data/.chaos/battery.profile; 
				cp -a /res/customconfig/battery.profile /data/.chaos/;
				echo "battery" > /data/.chaos/.active.profile;
				$BB sh /res/user_uci_test_run.sh > /dev/null;
			)&
		;;
		4)
			(
				rm -f /data/.chaos/default.profile; 
				cp -a /res/customconfig/default.profile /data/.chaos/;
				echo "default" > /data/.chaos/.active.profile;
				$BB sh /res/user_uci_test_run.sh > /dev/null;
			)&
		;;
		5)
			(
				rm -f /data/.chaos/performance.profile; 
				cp -a /res/customconfig/performance.profile /data/.chaos/;
				echo "performance" > /data/.chaos/.active.profile;
				$BB sh /res/user_uci_test_run.sh > /dev/null;
			)&
		;;
		*)
		;;
	esac;
else
	# Anti smart user protection! multi run of this script will bring HELL!
	echo "A profile restoration is already in process. Please try later.";
fi;
