#!/sbin/busybox sh
if [ `pgrep -f push-actions/fix_media |  wc -l` \< 3 ]; then
(
echo "Fixing and then rescanning media. Rescanning media will take time depending on size & content of your sdcard."
pm disable com.android.providers.media/com.android.providers.media.MediaScannerReceiver;
if [ -e /sdcard/Android/data/ ]; then
	$BB rm -rf /sdcard/Android/data/com.cooliris.media;
	$BB rm -rf /sdcard/Android/data/com.android.gallery3d;
	$BB rm -rf /sdcard/Android/data/com.google.android.gallery3d;
	$BB rm -rf /sdcard/Android/data/com.android.providers.media;
	$BB rm -rf /sdcard/Android/data/com.google.android.music;
	$BB rm -rf /data/data/com.android.providers.media/databases/*;
fi;
pm enable com.android.providers.media/com.android.providers.media.MediaScannerReceiver;
sleep 2;
pm disable com.android.providers.media/com.android.providers.media.MediaScannerReceiver;
sleep 1;
pm enable com.android.providers.media/com.android.providers.media.MediaScannerReceiver;
)&
else
	# Anti smart user protection!
	echo "Media fixing is already in progress!";
	echo "Please wait!";
fi;
