#!/sbin/busybox sh

PROFILE=`cat /data/.chaos/.active.profile`;
. /data/.chaos/${PROFILE}.profile;

if [ "$ksm_control" == "on" ]; then
	saved_mem=`echo "Saved memory: $((\`cat /sys/kernel/mm/ksm/pages_sharing\`*4096/1024/1024)) MB"`;
	shard_mem=`echo "Shared memory: $((\`cat /sys/kernel/mm/ksm/pages_shared\`*4096/1024/1024)) MB"`;

	echo "$saved_mem - $shard_mem";
else
	echo "KSM IS DISABLED";
fi;
